version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_evergreen
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb:/data/db
    expose:
      - "27016"
    ports:
      - "27016:27017"


networks:
  default:
    external:
      name: external-example

volumes:
  mongodb:
